Feature/statistical measures
IIS-ZPI/ZPI2022_zaoczni_RzultePapaje pull request #27
Opened 2023-01-11 15:49 UTC by ckarczewski

2023-01-11 17:53 UTC, ShanghaiG approved these changes

2023-01-11 17:53 UTC, ShanghaiG commented on backend/zpiproject/urls.py
> +    path('', include('nbp.urls')),
why `admin/` path?

2023-01-11 18:00 UTC, ckarczewski commented on backend/zpiproject/urls.py
> +    path('', include('nbp.urls')),
added by default, we do not need to use it

2023-01-12 13:27 UTC, jowczar commented on backend/zpiproject/urls.py
> +    path('', include('nbp.urls')),
I can't see it running on the server, perhaps it's not set-up correctly on Vercel?
@ShanghaiG can you check it, we have now index GET / route here to test the build on

2023-01-12 13:28 UTC, jowczar commented on backend/nbp/helpers/statistical_measures.py
> +# test = [181, 187, 196, 196, 198, 203, 207, 211, 215, 123, 199]
rm unused code

2023-01-12 15:02 UTC, jowczar commented on backend/tests/test_statistical_measures.py
> +from django.test import TestCase
I added unit tests & boundary value tests.
Overall:
– handle zeros and empty arrays (you can get them from db if e.g. currency is no longer used)
– set some specific .toFixed() decimal points amount so it's testable
– there can be many modes if numbers in dataset have same counts – every calculator returns it as an array []

These tests FAIL for now so @ShanghaiG you may want to disable them if you are doing sth on CI

2023-01-12 15:02 UTC, jowczar requested changes
Fix cases covered by tests

2023-01-14 21:06 UTC, jowczar commented on backend/nbp/views.py
> +def measures(request):
I will add subtask to Functional tests in Jira for testing this piece of code

2023-01-14 22:50 UTC, merged

2023-01-14 22:50 UTC, jowczar approved these changes