Feature/docker containers
IIS-ZPI/ZPI2022_zaoczni_RzultePapaje pull request #37
Opened 2023-01-13 17:41 UTC by ShanghaiG

2023-01-14 21:53 UTC, jowczar requested changes

2023-01-14 21:53 UTC, jowczar commented on backend/zpiproject/settings.py
> +        'PASSWORD': "xudCP9r6YYH2aM4FSrf4JGyxLsy8EHD7",
dotenv

2023-01-14 21:53 UTC, jowczar commented on docker-compose.yml
> +      - POSTGRES_PASSWORD=xudCP9r6YYH2aM4FSrf4JGyxLsy8EHD7
Should be a .env file w/ .env.example
I think this works out of the box in docker, I don't recall any problems with that

2023-01-14 21:53 UTC, jowczar commented on backend/nbp/helpers/statistical_measures.py
> +import math
Why it has Czarek's changes if it's only Dockerfiles w/ docker-compose :rsus:

2023-01-14 21:53 UTC, jowczar commented on frontend/Dockerfile
> +RUN npm run build
You are running npm run build and then npm start but the start logs are saying it's a development server, not production build. I'd guess npm run build is building a static version of the app so it's either should be pointed at by entrypoint in nginx or we can just use the dev server; 2 of them at the same time seem obsolete but I didn't read into it so I may be wrong

https://stackoverflow.com/questions/50722133/what-exactly-is-the-react-scripts-start-command

2023-01-14 21:53 UTC, jowczar commented on docker-compose.yml
> +      - 3001:3000
This seems incorrect? in logs I can see the dev server is running on port 3000 inside the container
You are exposing 3001 and the traffic goes from there goes to 3000 so on localhost:3000 it's trying to reach :3001 port in the container
or is there some .env missing with ports set?

same w/ backend

2023-01-14 22:53 UTC, ShanghaiG commented on backend/nbp/helpers/statistical_measures.py
> +import math
i told you already, i had to merge them, because i couldnt work on dockerfile on backend (was not working)

2023-01-15 11:04 UTC, jowczar commented on backend/nbp/helpers/statistical_measures.py
> +import math
ok

2023-01-18 18:51 UTC, merged