Feature/currency comparison
IIS-ZPI/ZPI2022_zaoczni_RzultePapaje pull request #53
Opened 2023-01-18 21:19 UTC by ckarczewski

2023-01-19 09:26 UTC, jowczar commented on backend/nbp/views.py
> +1 2 3 4 5
what is this stuff?

2023-01-19 09:41 UTC, ckarczewski commented on backend/nbp/views.py
> +1 2 3 4 5
comment I forgot to delete

2023-01-19 11:49 UTC, ShanghaiG requested changes

2023-01-19 11:49 UTC, ShanghaiG commented on backend/nbp/urls.py
> +    path('currency_comparison', views.currency_comparison, name='currency comparison'),
that space inside currency comparision is a proper way to name path? Will it work ?

2023-01-19 11:49 UTC, ShanghaiG commented on backend/nbp/views.py
> +                query_B = TabelaB.objects.values_list('mid').filter(code=currency[i]).filter(country=currency[i])
Wouldnt it be better if search in TableA first, if found in TableA then DONT search in TableB?
What is the point in looping over TableB if data found in TableA?

2023-01-19 11:49 UTC, ShanghaiG commented on backend/nbp/views.py
> +
I think, TabelaA, TabelaB, TabelaC should be named in english as well

2023-01-19 22:03 UTC, ckarczewski commented on backend/nbp/views.py
> +                query_B = TabelaB.objects.values_list('mid').filter(code=currency[i]).filter(country=currency[i])
no

2023-01-19 22:19 UTC, ckarczewski commented on backend/nbp/views.py
> +
table names are imported from the database

2023-01-20 17:31 UTC, jowczar commented
answer comments

2023-01-20 17:32 UTC, jowczar requested changes
answer comments

2023-01-20 17:42 UTC, ckarczewski commented on backend/nbp/urls.py
> +    path('currency_comparison', views.currency_comparison, name='currency comparison'),
Probably my oversight, already fixed

2023-01-20 18:22 UTC, ShanghaiG commented on backend/nbp/views.py
> +                query_B = TabelaB.objects.values_list('mid').filter(code=currency[i]).filter(country=currency[i])
ok, thanks for answering!

2023-01-20 18:23 UTC, ShanghaiG approved these changes

2023-01-22 09:06 UTC, jowczar approved these changes

2023-01-22 09:06 UTC, merged